disable_existing_loggers: false
formatters:
  access:
    (): uvicorn.logging.AccessFormatter
    fmt: '%(asctime)s %(levelprefix)s %(client_addr)s - "%(request_line)s" %(status_code)s'
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: '%(asctime)s %(levelprefix)s %(message)s'
    use_colors: null
handlers:
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr
loggers:
  uvicorn:
    handlers:
    - default
    level: INFO
  uvicorn.access:
    handlers:
    - access
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
version: 1
