name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      full_tests:
        description: "Run the full test suite"
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  config:
    name: Unit Test Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      env:
        FULL_TESTS: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.full_tests) || contains(github.event.pull_request.labels.*.name, 'full-tests') }}
      run: |
        if [[ "$FULL_TESTS" == "true" ]]; then
          matrix='{
            "use-ipykernel": [true, false],
            "python-env": ["py311", "py312", "py313", "py314"],
            "zmq-encoding": ["json", "msgpack"],
            "splits": [3],
            "group": [1, 2, 3],
            "exclude": [
              {"python-env": "py311", "zmq-encoding": "msgpack"},
              {"python-env": "py312", "zmq-encoding": "msgpack"},
              {"python-env": "py313", "zmq-encoding": "msgpack"}
            ]
          }'
        else
          matrix='{
            "use-ipykernel": [true, false],
            "python-env": ["py314"],
            "zmq-encoding": ["json"],
            "splits": [10],
            "group": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          }'
        fi
        echo "matrix=$(jq -c . <<< "$matrix")" >> "$GITHUB_OUTPUT"

  build:
    needs: config
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.config.outputs.matrix) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        # Need this to get version number from last tag
        fetch-depth: 0
    - uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: "7.x"
    - uses: prefix-dev/setup-pixi@v0.10.0
    - name: Install dependencies
      run: |
        pixi install --environment=${{ matrix.python-env }}
        pixi list --environment=${{ matrix.python-env }}
        pixi run --environment=${{ matrix.python-env }} pip list
        pixi run --environment=${{ matrix.python-env }} conda list

    - name: Test with pytest
      env:
        USE_IPYKERNEL: ${{ matrix.use-ipykernel }}
        USE_ZMQ_ENCODING: ${{ matrix.zmq-encoding }}
      run: |
        # pytest -k test_ip_kernel_func -vvv
        pixi run --environment=${{ matrix.python-env }} coverage run -m pytest -vv --splits ${{ matrix.splits }} --group ${{ matrix.group }}
        pixi run --environment=${{ matrix.python-env }} coverage report -m
